Don't hide access tokens
HPI-SWA-Teaching/AutoTDD pull request #106
Opened 2021-06-25 20:40 UTC by SebastianWagner2

Closes: #90 
Contributes to: #65

Added class comments to a few classes
Load access tokens of remote testing entities into corresponding editor

2021-06-25 21:16 UTC, kolioOtSofia approved these changes

2021-06-25 21:17 UTC, Benjamin-Frost requested changes

2021-06-25 21:17 UTC, Benjamin-Frost commented on packages/AutoTDD-Core.package/ATDDGitHubActionsRepository.class/README.md
> +An ATDDGitHubActionsRepository facilitates the GHAClient and GHAParser to provide structured data.
We never use the short version `GHAParser`. We should write it out here as well. Same for `GHAClient`

2021-06-26 16:26 UTC, Benjamin-Frost approved these changes

2021-06-26 16:26 UTC, merged