adding tests for Remote Client and GHA Repository
HPI-SWA-Teaching/AutoTDD pull request #114
Opened 2021-06-29 08:50 UTC by kolioOtSofia

Closes: #Issue

2021-07-02 14:58 UTC, SebastianWagner2 requested changes

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsRepositoryTest.class/instance/tearDown.st
> +	mockAPI destroy
```suggestion
	mockAPI destroy.
	super tearDown
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsRepositoryTest.class/instance/testInitialization.st
> +
```suggestion
	| newClient |

	newClient := ATDDGitHubActionsClient new. 
	repository client: newClient.
	self assert: repository client equals: newClient
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsRepositoryTest.class/instance/testRequireRepository.st
> +	self assert: repository requireRepository equals: (Json readFrom: ATDDGitHubActionMockAPI defaultRuns readStream)
```suggestion
tests
testRequireRepository
	
	self assert: repository requireRepository equals: (Json readFrom: ATDDGitHubActionMockAPI defaultRuns readStream)
```
I am not sure if the line I took out does anything or not

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/setUp.st
> +	windowsToDelete add: resultsWindow
```suggestion
running
setUp

	| client |

	super setUp.
	gitHubAction := ATDDGitHubAction new.
	client := ATDDGitHubActionsClient new.
	client apiUrl: 'http://localhost:9999/'.
	gitHubAction
		pause;
		repositoryURL: 'hpi-swa-teaching/AutoTDD'.
	gitHubAction repository client: client.
	mockApi := ATDDGitHubActionMockAPI new.
	resultsWindow := ATDDGitHubActionResults openForTarget: gitHubAction.
	windowsToDelete := OrderedCollection new.
	windowsToDelete add: resultsWindow
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/tearDown.st
> +
```suggestion
running
tearDown

	gitHubAction delete.
	mockApi destroy.
	windowsToDelete do: [:each | each changed: #close ]
	super tearDown.
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testAnsiParsing.st
> +	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #failure)
```suggestion
tests
testAnsiParsing

	| sampleString parsedString |

	sampleString := '2021-05-23T12:57:07.9111495Z [0m[32m ✓[0m #testInitialization (0ms)[0m'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'PASS') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #successful).

	sampleString := '2021-05-23T12:57:07.9111495Z [0m[31m ✓[0m #testInitialization (0ms)[0m'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'ERROR') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #error).

	sampleString := '2021-05-23T12:57:07.9111495Z [0m[33m ✓[0m #testInitialization (0ms)[0m'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'FAIL') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #failure)
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testIsSmalltalkCiLog.st
> +	self assert: (resultsWindow isSmalltalkCILog: sampleString) equals: true
```suggestion
	sampleString := 'I dont know, this is some text that is not a valid log'.
	self assert: (resultsWindow isSmalltalkCILog: sampleString) equals: false.
	sampleString :=
		'This is some log,
		some more log
		Run hpi-swa/setup-smalltalkCI
		some more log'.
	self assert: (resultsWindow isSmalltalkCILog: sampleString) equals: true
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testParsingSmalltalkCILog.st
> +	self assert: (parsedResult asString includesSubstring: '2021-05-23T12') equals: false.
```suggestion
tests
testParsingSmalltalkCILog

	| parsedResult |

	parsedResult := resultsWindow parseSmalltalkCILog: self sampleSmalltalkLog.
	self assert: parsedResult hasColorAttribute equals: true.
	"does not include time-stamps"
	self assert: (parsedResult asString includesSubstring: '2021-05-23T12') equals: false.
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/setUp.st
> +
```suggestion
running
setUp

	client := ATDDRemoteClient new
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/testErrorDictionary.st
> +	self assert: (errorDictionary at: 404) = ATDDNotFoundError
```suggestion
tests
testErrorDictionary

	| errorDictionary |

	errorDictionary := client errorDictionary.
	self assert: (errorDictionary at: 401) = ATDDConnectionError.
	self assert: (errorDictionary at: 403) = ATDDAccessDeniedError.
	self assert: (errorDictionary at: 404) = ATDDNotFoundError
```

2021-07-02 14:58 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/testThrowExceptionForResponseCode.st
> +
```suggestion
tests
testThrowExceptionForResponseCode

	self should: [client throwExceptionForResponseCode: 401] raise: ATDDConnectionError.
	self should: [client throwExceptionForResponseCode: 403] raise: ATDDAccessDeniedError. 
	self should: [client throwExceptionForResponseCode: 404] raise: ATDDNotFoundError
```

2021-07-03 12:03 UTC, SebastianWagner2 requested changes

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsRepositoryTest.class/instance/tearDown.st
> +tearDown
```suggestion
tearDown
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsRepositoryTest.class/instance/testInitialization.st
> +	newClient := ATDDGitHubActionsClient new.
```suggestion
	newClient := ATDDGitHubActionsClient new.
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/tearDown.st
> +
```suggestion
running
tearDown
	
	super tearDown.
	gitHubAction delete.
	mockApi destroy.
	windowsToDelete do: [ :each | each changed: #close ].
	super tearDown
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testIsSmalltalkCiLog.st
> +	sampleString :=
```suggestion
	sampleString :=
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testParsingSmalltalkCILog.st
> +	self assert: (parsedResult asString includesSubstring: '2021-05-23T12') equals: false.
```suggestion
	self assert: (parsedResult asString includesSubstring: '2021-05-23T12') equals: false
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/testErrorDictionary.st
> +testErrorDictionary
```suggestion
testErrorDictionary
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/setUp.st
> +	client := ATDDRemoteClient new
```suggestion
running
setUp

	super setUp.
	client := ATDDRemoteClient new
```

2021-07-03 12:03 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDRemoteClientTest.class/instance/testThrowExceptionForResponseCode.st
> +
```suggestion
tests
testThrowExceptionForResponseCode

	self should: [client throwExceptionForResponseCode: 401] raise: ATDDConnectionError.
	self should: [client throwExceptionForResponseCode: 403] raise: ATDDAccessDeniedError.
	self should: [client throwExceptionForResponseCode: 404] raise: ATDDNotFoundError
```

2021-07-03 12:05 UTC, SebastianWagner2 requested changes

2021-07-03 12:05 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDGitHubActionsResultsTests.class/instance/testAnsiParsing.st
> +	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #failure)
```suggestion
tests
testAnsiParsing

	| sampleString parsedString |
	
	sampleString := '...'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'PASS') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #successful).
	
	sampleString := '...'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'ERROR') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #error).
	
	sampleString := '...'.
	parsedString := resultsWindow parseAnsiCodeOf: sampleString.
	self assert: parsedString hasColorAttribute equals: true.
	self assert: (parsedString asString includesSubstring: 'FAIL') equals: true.
	self assert: (parsedString colorAt: 3) equals: (resultsWindow colorForStatus: #failure)
```

Replace the dots with the original string though

2021-07-03 19:04 UTC, SebastianWagner2 approved these changes

2021-07-04 14:57 UTC, Benjamin-Frost approved these changes

2021-07-04 14:58 UTC, merged