Adding more tests
HPI-SWA-Teaching/AutoTDD pull request #121
Opened 2021-07-06 11:39 UTC by kolioOtSofia

Closes: #Issue

2021-07-06 20:48 UTC, SebastianWagner2 requested changes

2021-07-06 20:48 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDBrowserTests.class/instance/testEditGitHubAction.st
> +	windowsToDelete add: editor
Not sure this is testing the edit function

2021-07-06 20:48 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDBrowserTests.class/instance/testEditGitHubAction.st
> +	windowsToDelete add: editor
Probably not intended to exist anymore (in testEditPauseReults i suppose)

2021-07-06 20:48 UTC, SebastianWagner2 commented on packages/AutoTDD-Tests.package/ATDDBrowserTests.class/instance/testOpenProfileEditor.st
> +	windowsToDelete add: window
```suggestion
tests
testOpenProfileEditor

	| amount window |
	
	amount := ATDDProfileEditor allInstances size.
	window := browser openProfileEditor.
	self assert: ATDDProfileEditor allInstances size = (amount + 1).
	windowsToDelete add: window
```
Thanks for adding that, my bad :D

2021-07-07 17:28 UTC, Benjamin-Frost approved these changes

2021-07-07 17:45 UTC, SebastianWagner2 approved these changes

2021-07-07 17:45 UTC, merged