Issue/33 tutorial
HPI-SWA-Teaching/AutoTDD pull request #83
Opened 2021-06-11 14:06 UTC by SebastianWagner2

Contributes to: #33

If the ATDDBrowser is opened for the first time on a Squeak image, the user is presented with the tutorial.

2021-06-11 14:29 UTC, Toalaah approved these changes

2021-06-12 06:55 UTC, Benjamin-Frost requested changes

2021-06-12 06:55 UTC, Benjamin-Frost commented on packages/AutoTDD-Core.package/ATDDHelper.class/class/openHelpPrompt.st
> +	answer :=  UserDialogBoxMorph confirm: 'Would you like to view a tutorial on ATDD?'  title: 'Input requested'.
Probably we shouldn't use the short form when introducing the application

```suggestion
	answer :=  UserDialogBoxMorph confirm: 'Would you like to view a tutorial on AutoTDD?'  title: 'Input requested'.
```

2021-06-12 07:11 UTC, kolioOtSofia approved these changes

2021-06-13 07:56 UTC, Benjamin-Frost approved these changes

2021-06-13 08:08 UTC, merged