Add Checkbox to simplify Smalltalk CI Logs
HPI-SWA-Teaching/AutoTDD pull request #94
Opened 2021-06-18 14:48 UTC by Benjamin-Frost

Closes: #89

2021-06-18 23:45 UTC, SebastianWagner2 requested changes

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/buildSimplifySmalltalkCiLogCheckBoxWith..st
> +		yourself
```suggestion
building
buildSimplifyLogCheckBoxWith: aBuilder

	^ aBuilder pluggableCheckBoxSpec new
		model: self;
		label: #simplifyLogCheckBoxLabel;
		action: #simplifyLogCheckBoxAction;
		state: #simplifyLogCheckBoxState;
		yourself
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/shouldSimplifySmalltalkCiLog..st
> +	shouldSimplifySmalltalkCiLog := aBoolean
```suggestion
accessing
shouldSimplifyLog: aBoolean
	
	shouldSimplifyLog := aBoolean
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/shouldSimplifySmalltalkCiLog.st
> +	^ shouldSimplifySmalltalkCiLog ifNil: [ shouldSimplifySmalltalkCiLog := false ]
```suggestion
accessing
shouldSimplifyLog
	
	^ shouldSimplifyLog ifNil: [ shouldSimplifyLog := false ]
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/simplifySmalltalkCiLogCheckBoxAction.st
> +	self updateJobLogForId: ( (self jobs at: selectedJob) id )
```suggestion
some other category not sure
simplifyLogCheckBoxAction
	
	self shouldSimplifyLog: self shouldSimplifyLog not.
	self updateJobLogForId: (self jobs at: selectedJob) id
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

Idk if the parenthesis are necessary

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/simplifySmalltalkCiLogCheckBoxFrame.st
> +		yourself
```suggestion
building
simplifyLogCheckBoxFrame
	
	^ LayoutFrame new
		leftFraction: 0.3 offset: 0;
		topFraction: 0.3 offset: 0;
		rightFraction: 1 offset: 0;
		bottomFraction: 0.3 offset: self class defaultCheckBoxHeight;
		yourself
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/simplifySmalltalkCiLogCheckBoxLabel.st
> +	^ 'Simplify SmalltalkCI Log'
```suggestion
accessing
simplifyLogCheckBoxLabel
	
	^ 'Simplify ' , _fetch String here instead_ , ' Log'
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

Would put this String in this class to allow for reusability for potential simplification option of travis status log (then we could move all this code to ATDDRemoteResults)

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/simplifySmalltalkCiLogCheckBoxState.st
> +	^ self shouldSimplifySmalltalkCiLog
```suggestion
accessing
simplifyLogCheckBoxState
	
	^ self shouldSimplifyLog
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDGitHubActionResults.class/instance/updateJobLogForId..st
> +		].
```suggestion
	(self shouldSimplifyLog)
		ifTrue: [
			(self isSmalltalkCILog: response)
				ifTrue: [response := self parseSmalltalkCILog: response].
		].
```
I felt the names were a little too long to support readability. Although the parsing is in the same class i would not include any info on implementation (SmalltalkCiLog vs Log) in GUI code

2021-06-18 23:45 UTC, SebastianWagner2 commented on packages/AutoTDD-GUI.package/ATDDTravisStatusResults.class/instance/buildJobLogComponentsWith..st
> +				yourself);
```suggestion
			frame: self jobLogTextFrame;
			yourself);
```

2021-06-20 15:20 UTC, kolioOtSofia approved these changes

2021-06-20 15:25 UTC, SebastianWagner2 approved these changes

2021-06-20 16:20 UTC, merged